In [13]:
import numpy as np

In [33]:
#Print the NumPy version being used
print(np.__version__)

1.21.5


In [31]:
#Create array 
my_array = [1, 2, 3]
my_np_array = np.array(my_array)
my_np_array

array([1, 2, 3])

In [15]:
#Check data type of array 
my_np_array.dtype

dtype('int32')

In [32]:
#Create a 2D-array 
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#Verify dimension of arrays
print("The dimension of my_np_array is: " + str(my_np_array.ndim))
print("The dimension of my_2d_array is: " + str(my_2d_array.ndim))

The dimension of my_np_array is: 1
The dimension of my_2d_array is: 2


In [21]:
#Get the first element of my_np_array
print("The first element of my_np_array is: " + str(my_np_array[0]))

The first element of my_np_array is: 1


In [23]:
#Get the first array of my_2d_array 
print("The first array in my_2d_array is: " + str(my_2d_array[0]))

The first array in my_2d_array is: [1 2 3]


In [24]:
#Get the first element of the first array of my_2d_array and of the second array of my_2d_array
print("The first element of the first array in my_2d_array is: " + str(my_2d_array[0][0]))
print("The first element of the second array in my_2d_array is: " + str(my_2d_array[1][0]))

The first element of the first array in my_2d_array is: 1
The first element of the second array in my_2d_array is: 4


In [25]:
#Try the previous two tasks with an alternative indexing technique 
print("The first element of the first array in my_2d_array is: " + str(my_2d_array[0, 0]))
print("The first element of the second array in my_2d_array is: " + str(my_2d_array[1, 0]))

The first element of the first array in my_2d_array is: 1
The first element of the second array in my_2d_array is: 4


In [26]:
#Create array of numbers 1-5 
one_thru_five = np.array([1, 2, 3, 4, 5])

In [27]:
#Print an arrray of elements 1 through 3 using slicing 
print(str(one_thru_five[0:3]))

[1 2 3]


In [30]:
#Print an array of elements 3 through 5 using slicing
print(str(one_thru_five[2:5]))

[3 4 5]


In [36]:
#Print the sum of two np arrays 
a1 = np.array([[1, 1, 1], [2, 2, 2]])
a2 = np.array([[3, 3, 3], [4, 4, 4]])

sum_array = a1 + a2 
print(sum_array)

[[4 4 4]
 [6 6 6]]


In [37]:
#Print a1 multiplied by a scalar 
scalar = 5
mult_array = a1*scalar
print(mult_array)

[[ 5  5  5]
 [10 10 10]]


In [38]:
#Create a 5x5 identity matrix 
id_matrix_5 = np.eye(5)
id_matrix_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])